#!/usr/bin/env python3
"""Original Cupcake diagnostic cartridge; no imported ROM/BIOS/logo data.

A deliberately small ARMv4T assembler emits only the instructions below. The
program starts in ARM mode, configures GBA mode 4, draws palette-indexed regions,
then updates palettes on VBlank. No SDK, binary template or external assembler.
Generated bytes may only be written under this checkout's ignored .build/.
"""
import argparse
import hashlib
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]


def immediate(value):
    """ARM data-processing immediate: 8-bit integer rotated right by 2*n."""
    for rotation in range(16):
        shift = rotation * 2
        candidate = ((value << shift) | (value >> ((32 - shift) % 32))) & 0xFFFFFFFF
        if candidate <= 255:
            return (rotation << 8) | candidate
    raise ValueError("Immediate needs a literal load")


class ARM:
    def __init__(self):
        self.code = []
        self.labels = {}
        self.branches = []
        self.literals = []

    @property
    def position(self):
        return 0xC0 + len(self.code) * 4

    def label(self, name):
        assert name not in self.labels
        self.labels[name] = self.position

    def emit(self, word):
        self.code.append(word)

    def load(self, register, value):
        self.literals.append((len(self.code), register, value))
        self.emit(0)

    def data(self, operation, destination, first, value, *, register=False, flags=False, condition=14):
        opcodes = {"and": 0, "sub": 2, "add": 4, "tst": 8, "cmp": 10, "mov": 13}
        self.emit((condition << 28) | ((not register) << 25) | (opcodes[operation] << 21) |
                  ((flags or operation in ("cmp", "tst")) << 20) | (first << 16) |
                  (destination << 12) | (value if register else immediate(value)))

    def halfword(self, register, base, offset=0, *, load=False):
        assert 0 <= offset <= 255
        self.emit(0xE1C000B0 | (load << 20) | (base << 16) | (register << 12) |
                  ((offset & 0xF0) << 4) | (offset & 15))

    def byte(self, register, base, offset=0, *, load=False):
        assert 0 <= offset < 4096
        self.emit(0xE5C00000 | (load << 20) | (base << 16) | (register << 12) | offset)

    def branch(self, label, condition=14):
        self.branches.append((len(self.code), label, condition))
        self.emit(0)

    def finish(self):
        for index, label, condition in self.branches:
            delta = self.labels[label] - (0xC0 + index * 4 + 8)
            assert delta % 4 == 0
            self.code[index] = (condition << 28) | 0x0A000000 | ((delta // 4) & 0xFFFFFF)
        for index, register, value in self.literals:
            delta = self.position - (0xC0 + index * 4 + 8)
            assert 0 <= delta < 4096
            self.code[index] = 0xE59F0000 | (register << 12) | delta
            self.emit(value)
        return b"".join(struct.pack("<I", word) for word in self.code)


def fixture_bytes(*, sram_counter=False, sram_equal_write=False):
    if sram_equal_write:
        sram_counter = True
    a = ARM()
    # r0: IO base, r1: palette base, r2: current VRAM pointer.
    a.load(0, 0x04000000)
    a.load(1, 0x05000000)
    a.load(2, 0x06000000)
    a.load(3, 0x0484)  # Mode 4 + BG2, forced blank during drawing.
    a.halfword(3, 0)
    for index, color in enumerate((0, 0x001F, 0x03E0, 0x7C00)):
        a.load(3, color)
        a.halfword(3, 1, index * 2)
    a.load(3, 0x2108)  # 5-bit gray = 8, expanded by mGBA to 66 per channel.
    for index in range(8, 18):
        a.halfword(3, 1, index * 2)
    a.load(3, 0x7FE0)
    a.halfword(3, 1, 18 * 2)

    # Three 80-pixel-wide vertical RGB calibration bands, 160 scanlines.
    a.data("mov", 4, 0, 160)
    a.label("row")
    for band in range(1, 4):
        a.load(3, band * 0x0101)
        a.data("mov", 5, 0, 40)
        a.label(f"band_{band}")
        a.halfword(3, 2)
        a.data("add", 2, 2, 2)
        a.data("sub", 5, 5, 1, flags=True)
        a.branch(f"band_{band}", condition=1)  # NE
    a.data("sub", 4, 4, 1, flags=True)
    a.branch("row", condition=1)

    # Top 16 scanlines: animated palette entry 18.
    a.load(2, 0x06000000)
    a.load(3, 0x1212)
    a.load(4, 240 * 16 // 2)
    a.label("top")
    a.halfword(3, 2)
    a.data("add", 2, 2, 2)
    a.data("sub", 4, 4, 1, flags=True)
    a.branch("top", condition=1)

    # Bottom 32 scanlines: ten 24px indicators in GBA input-bit order.
    a.load(2, 0x06000000 + 240 * 128)
    a.data("mov", 4, 0, 32)
    a.label("indicator_row")
    for button in range(10):
        a.load(3, (button + 8) * 0x0101)
        a.data("mov", 5, 0, 12)
        a.label(f"indicator_{button}")
        a.halfword(3, 2)
        a.data("add", 2, 2, 2)
        a.data("sub", 5, 5, 1, flags=True)
        a.branch(f"indicator_{button}", condition=1)
    a.data("sub", 4, 4, 1, flags=True)
    a.branch("indicator_row", condition=1)

    # Channel 2 square tone. Both stereo sides enabled. Left/right volume 7/3.
    for offset, value in ((0x84, 0x80), (0x80, 0x2273), (0x82, 2),
                          (0x68, 0xF080), (0x6C, 0x8600), (0, 0x0404)):
        a.load(3, value)
        a.halfword(3, 0, offset)
    a.data("mov", 6, 0, 0)  # animation counter
    a.load(7, 0x04000130)  # KEYINPUT, active low
    if sram_counter:
        # Optional original save diagnostic. Byte 0 is a marker; byte 1 counts
        # released-to-held A edges modulo 256. Initialize only erased SRAM.
        # r10 = SRAM base, r11 = previous active-low A bit. Default is unchanged.
        a.load(10, 0x0E000000)
        a.byte(3, 10, load=True)
        a.data("cmp", 0, 3, 255)
        a.branch("sram_ready", condition=1)
        a.data("mov", 3, 0, 0x43)
        a.byte(3, 10)
        a.data("mov", 3, 0, 0)
        a.byte(3, 10, 1)
        a.label("sram_ready")
        a.data("mov", 11, 0, 1)
    a.label("wait_visible")
    a.halfword(3, 0, 6, load=True)  # VCOUNT
    a.data("cmp", 0, 3, 160)
    a.branch("wait_visible", condition=2)  # CS/HS
    a.label("wait_vblank")
    a.halfword(3, 0, 6, load=True)
    a.data("cmp", 0, 3, 160)
    a.branch("wait_vblank", condition=3)  # CC/LO
    a.halfword(8, 7, load=True)
    if sram_counter:
        a.data("tst", 0, 8, 1)
        a.branch("sram_no_edge", condition=1)
        a.data("cmp", 0, 11, 0)
        a.branch("sram_no_edge", condition=0)
        a.byte(3, 10, 1, load=True)
        if not sram_equal_write:
            a.data("add", 3, 3, 1)
        a.byte(3, 10, 1)
        a.label("sram_no_edge")
        a.data("and", 11, 8, 1)
    for button in range(10):
        a.load(3, 0x2108)
        a.data("tst", 0, 8, 1 << button)
        a.load(9, 0x03FF)  # pressed = yellow
        a.data("mov", 3, 0, 9, register=True, condition=0)  # EQ
        a.halfword(3, 1, (button + 8) * 2)
    a.data("add", 6, 6, 1)
    a.load(3, 0x7FE0)  # cyan
    a.load(9, 0x7C1F)  # magenta
    a.data("tst", 0, 6, 16)
    a.data("mov", 3, 0, 9, register=True, condition=1)
    a.halfword(3, 1, 18 * 2)
    # Holding B swaps left/right volumes, making channel order observable.
    a.load(3, 0x2273)
    a.load(9, 0x2237)
    a.data("tst", 0, 8, 2)
    a.data("mov", 3, 0, 9, register=True, condition=0)
    a.halfword(3, 0, 0x80)
    a.branch("wait_visible")

    rom = bytearray(4096)
    # Original ARM B to 0xC0. Logo space 0x04..0x9F is deliberately all zero.
    struct.pack_into("<I", rom, 0, 0xEA00002E)
    rom[0xA0:0xAC] = b"CUPCAKE DIAG"
    rom[0xAC:0xB0] = b"CC01"
    rom[0xB0:0xB2] = b"00"
    rom[0xB2] = 0x96
    rom[0xBD] = (-sum(rom[0xA0:0xBD]) - 0x19) & 255
    code = a.finish()
    assert len(code) <= len(rom) - 0xC0
    rom[0xC0:0xC0 + len(code)] = code
    return bytes(rom)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("output", type=Path)
    parser.add_argument("--sram-counter", action="store_true",
                        help="Original SRAM marker/A-edge counter variant")
    parser.add_argument("--sram-equal-write", action="store_true",
                        help="A-edge writes the existing SRAM byte unchanged")
    args = parser.parse_args()
    output = args.output.resolve()
    if not output.is_relative_to(ROOT / ".build"):
        parser.error("Generated cartridge must stay under this checkout's ignored .build/")
    output.parent.mkdir(parents=True, exist_ok=True)
    content = fixture_bytes(sram_counter=args.sram_counter, sram_equal_write=args.sram_equal_write)
    output.write_bytes(content)
    print(f"Original diagnostic: {len(content)} bytes; SHA-256 {hashlib.sha256(content).hexdigest()}")


if __name__ == "__main__":
    main()
